dist: focal
language: python

python:
  - '3.9'
  - '3.12'

before_install:
  - pip install --upgrade pip setuptools packaging
  - if ! [ -f ./src/GRCh37.tar.gz ]; then wget ftp://alexandrovlab-ftp.ucsd.edu/pub/tools/SigProfilerMatrixGenerator/GRCh37.tar.gz -P ./src/; fi

install:
  - pip install .[tests]

cache:
  directories:
    - $TRAVIS_BUILD_DIR/src/

before_script:
  - python install_genome.py -l $TRAVIS_BUILD_DIR/src/ GRCh37

script:
  # run unit tests
  - pytest tests
  # run integration test
  - python3 test.py -t GRCh37

