dist: focal
language: python

branches:
  only:
    - master

python:
  - '3.9'
  - '3.12'

services:
  - docker

before_install:
  - pip install --upgrade pip setuptools packaging
  - if ! [ -f ./src/GRCh37.tar.gz ]; then wget --connect-timeout=10 --tries=20 ftp://alexandrovlab-ftp.ucsd.edu/pub/tools/SigProfilerMatrixGenerator/GRCh37.tar.gz -P ./src/; fi

install:
  - pip install .[tests]

cache:
  directories:
    - $TRAVIS_BUILD_DIR/src/

before_script:
  - python install_genome.py -l $TRAVIS_BUILD_DIR/src/ GRCh37

script:
  # run unit tests
  - pytest tests
  # run integration test
  - python3 test.py -t GRCh37

after_success:
  - |
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_PYTHON_VERSION" == "3.12" ]; then
      echo "Starting Docker deployment to GHCR for alexandrovlab..."

      VERSION_TAG=$(grep "VERSION = " setup.py | cut -d'"' -f2)

      # Get the repository name and convert it to lowercase
      REPO_NAME=$(basename $TRAVIS_REPO_SLUG | tr '[:upper:]' '[:lower:]')
      IMAGE_NAME="ghcr.io/alexandrovlab/$REPO_NAME"

      echo "Building version: $VERSION_TAG for image: $IMAGE_NAME"

      echo "$GHCR_PASSWORD" | docker login ghcr.io -u "$GHCR_USERNAME" --password-stdin

      docker build \
        --build-arg COMMIT_SHA=$TRAVIS_COMMIT \
        -t $IMAGE_NAME:$VERSION_TAG \
        -t $IMAGE_NAME:latest .

      docker push $IMAGE_NAME:$VERSION_TAG
      docker push $IMAGE_NAME:latest

      echo "Docker deployment to GHCR successful"
    else
      echo "Skipping Docker deployment"
    fi

